version: '3'

services:
  djangoapp:
    build: .
    container_name: selfreceipe_djangoapp_1
    volumes:
      - .:/opt/services/djangoapp/src
      - ./djangoapp-entrypoint.sh:/opt/services/djangoapp/src/djangoapp-entrypoint.sh
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    networks:
      - nginx_network
      - database1_network
      - database2_network
    depends_on:
      - database1
      - database2
    tty: true
    restart: always
    #command: python /opt/services/djangoapp/src/self_receipe/manage.py migrate --noinput
    command:
      - /opt/services/djangoapp/src/djangoapp-entrypoint.sh

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:10.1-alpine
#    ports:
#      - 8001:5432 
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  database2:
    image: postgres:10.1-alpine
#    ports:
#      - 8002:5433 
    env_file:
      - config/db/database2_env
    networks:
      - database2_network
    volumes:
      - postgres_data2:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
  database2_network:
    driver: bridge

volumes:
  postgres_data1:
  postgres_data2:
  static_volume:
  media_volume:
